// apps/core/src/App.svelte
<script>
  import Link from './component/Link.svelte'

  export let name
</script>

<style>
  main {
    text-align: center;
    padding: 1em;
    max-width: 240px;
    margin: 0 auto;
  }

  h1 {
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4em;
    font-weight: 100;
  }

  @media (min-width: 640px) {
    main {
      max-width: none;
    }
  }
</style>

<main>
  <h1>Hello {name}!</h1>
  <p>
    Visit the
    <Link url="https://svelte.dev/tutorial" text="Svelte tutorial" />
    to learn how to build Svelte apps.
  </p>
</main>

// apps/core/src/App.jsx
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Link_1 = require("./component/Link");
function App(props) {
    const { name } = props;
    <main>
        <h1>Hello {name}!</h1>
        <p>Visit the <Link_1.default url="https://svelte.dev/tutorial" text="Svelte tutorial"/> to learn how to build Svelte apps.</p>
    </main>;
}
exports.default = App;
